/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.media[_ngcontent-%COMP%] { \n    margin-bottom: 30px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3ZlbGFuL0Rvd25sb2Fkcy9kZXBsb3ktZGVtby9zcmMvYXBwL2dpdGh1Yi1mb2xsb3dlcnMvZ2l0aHViLWZvbGxvd2Vycy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3ZlbGFuL0Rvd25sb2Fkcy9kZXBsb3ktZGVtby9zcmMvYXBwL2dpdGh1Yi1mb2xsb3dlcnMvZ2l0aHViLWZvbGxvd2Vycy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
